server:
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gym_app
    username: postgres
    password: 91926499
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_second_level_cache: true
        use_query_cache: true
        factory_class: org.hibernate.cache.jcache.JCacheRegionFactory

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %highlight(%-5level) %cyan(%logger{36}) - %msg - TransactionId: %yellow(%X{transactionId}) %n"
  level:
    root: debug
